### ISSUE TITLE
There are 2 demos, and the act differently

### ISSUE THREAD

**Issue by ArtskydJ** [tobiaslabs/hex2words#9]
There are 2 demos right now, both of which are linked to [here](https://github.com/tobiaslabs/hex2words/tree/gh-pages)

- http://tobiaslabs.com/hex2words/
  - I think this is the newer of the two.
  - This one says 'at least 4 chars long' but supports 2.
  - Links are all good.
  - No favicon.
  - The link to it is in the github 'website' field.
- http://hex2words.tobiaslabs.com/
  - I think this is the older of the two.
  - This one says 'at least 4 chars long' and enforces it.
  - Github and demo source links are dead.
  - Favicon of an orange star.
  - The link to it is in the readme.

**Comment by saibotsivad** [comment]
Oh, thanks for the info! I deleted the subdomain, those are a pain to manage, and I'm just using Github pages anyway. I updated the first one, but as I don't have a custom favicon yet I just left it without for now.
